/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shadow.cloud.tech.common;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
