/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shadow.cloud.tech.common;

import com.google.gson.Gson;

public class Library {
    public boolean someLibraryMethod() {
        return true;

    }
}
